[window]
decorations = "Buttonless"
dynamic_padding = false
opacity = 1
blur = true
option_as_alt = "Both"
decorations_theme_variant = "Dark"

[window.padding]
x = 5
y = 5

[font]
size=16

[font.normal]
family = "MonoLisaPatch Nerd Font"
style = "Regular" 
[font.bold]
style = "Bold"
[font.italic]
style = "Italic"
[font.bold_italic]
style = "Bold Italic"

[font.offset]
y = 2

[scrolling]
history = 10000

[mouse]
hide_when_typing = true

[general]

live_config_reload = true
import = [
    "~/.config/alacritty/themes/kanagawa.toml"
]
