#!/usr/bin/env zsh

if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="stow,git,zsh,bat,tmux,nvim,yabai,skhd,bin,zed,kitty,ghostty,claude"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/dotfiles
fi
