local M = {}


--- @param opts GithubDarkMin.Options
M.setup = function(p, opts)
    return {
        -- Editor highlights
        ColorColumn                 = { bg = p.bg_lighter },
        Cursor                      = { fg = p.bg, bg = p.blue },
        CursorColumn                = { bg = p.bg_lighter },
        CursorLine                  = { bg = p.bg_lighter },
        CursorLineNr                = { fg = p.fg },
        CurSearch                   = { link = 'IncSearch' },
        Directory                   = { fg = p.blue },
        ErrorMsg                    = { fg = p.error },
        FloatBorder                 = { fg = p.border, bg = p.bg_lighter },
        FoldColumn                  = { fg = p.fg_dim, bg = p.bg },
        Folded                      = { fg = p.fg_dim, bg = p.bg_lighter },
        IncSearch                   = { fg = p.bg, bg = p.orange, bold = true },
        LineNr                      = { fg = p.fg_dim },
        MatchParen                  = { fg = p.cyan_light, bg = p.visual, bold = true },
        ModeMsg                     = { fg = p.fg },
        MoreMsg                     = { fg = p.blue },
        NonText                     = { fg = p.fg_dim },
        Normal                      = { fg = p.fg, bg = opts.transparent and 'NONE' or p.bg },
        NormalFloat                 = { fg = p.fg, bg = p.bg_lighter },
        Pmenu                       = { fg = p.fg, bg = p.bg_lighter },
        PmenuSbar                   = { bg = p.bg_lighter },
        PmenuSel                    = { bg = p.selection },
        PmenuThumb                  = { bg = p.fg_dim },
        Question                    = { fg = p.blue },
        Search                      = { bg = p.search, fg = p.fg },
        SignColumn                  = { bg = p.bg },
        SpecialKey                  = { fg = p.fg_dim },
        StatusLine                  = { fg = p.fg, bg = p.bg_lighter },
        StatusLineNC                = { fg = p.fg_dim, bg = p.bg_lighter },
        TabLine                     = { fg = p.fg_dim, bg = p.bg_lighter },
        TabLineFill                 = { bg = p.bg_darker },
        TabLineSel                  = { fg = p.fg, bg = p.bg },
        Title                       = { fg = p.blue, bold = true },
        VertSplit                   = { fg = p.border },
        Visual                      = { bg = p.visual },
        WarningMsg                  = { fg = p.warning },
        Whitespace                  = { fg = p.fg_dim },
        WinSeparator                = { fg = p.border },
        Added                       = { fg = p.git_add, bg = p.diff_add, bold = true },
        Changed                     = { fg = p.git_change, bg = p.diff_change, bold = true },
        Removed                     = { fg = p.git_delete, bg = p.diff_delete, bold = true },

        -- Syntax highlighting
        Boolean                     = { fg = p.cyan_light },
        Character                   = { fg = p.red },
        Comment                     = { fg = p.comment, italic = true },
        Conditional                 = { fg = p.red },
        Constant                    = { fg = p.cyan_light },
        Debug                       = { fg = p.red },
        Define                      = { fg = p.red },
        Delimiter                   = { fg = p.fg },
        Error                       = { fg = p.error },
        Exception                   = { fg = p.red },
        Float                       = { fg = p.cyan_light },
        Function                    = { fg = p.purple_light },
        Identifier                  = { fg = p.fg },
        Ignore                      = { fg = p.fg_dim },
        Include                     = { fg = p.red },
        Keyword                     = { fg = p.red },
        Label                       = { fg = p.red },
        Macro                       = { fg = p.red },
        Number                      = { fg = p.cyan_light },
        Operator                    = { fg = p.operator },
        PreCondit                   = { fg = p.red },
        PreProc                     = { fg = p.red },
        Repeat                      = { fg = p.red },
        Special                     = { fg = p.red },
        SpecialChar                 = { fg = p.red },
        SpecialComment              = { link = 'Comment' },
        Statement                   = { fg = p.red },
        StorageClass                = { fg = p.red },
        String                      = { fg = p.green_light },
        Structure                   = { fg = p.purple_light },
        Tag                         = { fg = p.green_light },
        Todo                        = { fg = p.purple, bold = true },
        Type                        = { fg = p.blue_light },
        Typedef                     = { link = 'Type' },
        Underlined                  = { fg = p.blue, underline = true },

        -- Treesitter highlights
        ['@text.literal']           = { fg = p.cyan_light },
        ['@text.reference']         = { fg = p.blue },
        ['@text.title']             = { fg = p.blue, bold = true },
        ['@text.uri']               = { fg = p.blue, underline = true },
        ['@text.underline']         = { underline = true },
        ['@text.todo']              = { fg = p.purple, bold = true },
        ['@comment']                = { link = 'Comment' },
        ['@punctuation']            = { fg = p.operator },
        ['@constant']               = { fg = p.cyan_light },
        ['@constant.builtin']       = { fg = p.cyan_light },
        ['@constant.macro']         = { fg = p.cyan_light },
        ['@define']                 = { fg = p.red },
        ['@macro']                  = { fg = p.red },
        ['@string']                 = { link = 'String' },
        ['@string.escape']          = { fg = p.green_light },
        ['@string.special']         = { link = 'Special' },
        ['@character']              = { link = 'Character' },
        ['@character.special']      = { link = 'Character' },
        ['@number']                 = { link = 'Number' },
        ['@boolean']                = { link = 'Boolean' },
        ['@float']                  = { link = 'Float' },
        ['@function']               = { fg = p.purple_light },
        ['@function.builtin']       = { fg = p.purple_light },
        ['@function.macro']         = { fg = p.purple_light },
        ['@parameter']              = { fg = p.fg },
        ['@method']                 = { fg = p.purple_light },
        ['@field']                  = { fg = p.fg },
        ['@property']               = { fg = p.fg },
        ['@constructor']            = { fg = p.purple_light },
        ['@conditional']            = { fg = p.red },
        ['@repeat']                 = { fg = p.red },
        ['@label']                  = { fg = p.red },
        ['@operator']               = { link = 'Operator' },
        ['@keyword']                = { fg = p.red },
        ['@module.go']              = { fg = p.fg },
        ['@exception']              = { fg = p.red },
        ['@variable']               = { fg = p.fg },
        ['@variable.builtin']       = { fg = p.red },
        ['@variable.member']        = { fg = p.fg },
        ['@type']                   = { link = 'Type' },
        ['@type.definition']        = { link = 'Typedef' },
        ['@type.builtin']           = { link = 'Type' },
        ['@storageclass']           = { fg = p.red },
        ['@namespace']              = { fg = p.fg },
        ['@include']                = { fg = p.red },
        ['@preproc']                = { fg = p.red },
        ['@debug']                  = { fg = p.red },
        ['@tag']                    = { fg = p.blue_light },
        ['@tag.attribute']          = { fg = p.fg },
        ['@tag.delimiter']          = { fg = p.fg },
        ['@tag.builtin']            = { link = 'Tag' },

        -- LSP highlights
        DiagnosticError             = { fg = p.error },
        DiagnosticWarn              = { fg = p.warning },
        DiagnosticInfo              = { fg = p.info },
        DiagnosticHint              = { fg = p.hint },
        DiagnosticUnnecessary       = { fg = p.comment },
        DiagnosticUnderlineError    = { sp = p.error, undercurl = true },
        DiagnosticUnderlineWarn     = { sp = p.warning, undercurl = true },
        DiagnosticUnderlineInfo     = { sp = p.info, undercurl = true },
        DiagnosticUnderlineHint     = { sp = p.hint, undercurl = true },
        LspReferenceText            = { bg = p.selection },
        LspReferenceRead            = { bg = p.selection },
        LspReferenceWrite           = { bg = p.selection },
        LspSignatureActiveParameter = { fg = p.orange, bold = true },

        -- Git signs
        GitSignsAdd                 = { fg = p.git_add },
        GitSignsChange              = { fg = p.git_change },
        GitSignsDelete              = { fg = p.git_delete },

        -- Quickfix
        QuickFixLine                = { bg = p.selection, bold = true },
        qfLineNr                    = { link = 'LineNr' },
        qfFileName                  = { link = 'Directory' },

        -- Diff
        DiffviewAdd                 = { bg = p.diff_add, bold = true },
        DiffviewChange              = { bg = p.diff_change, bold = true },
        DiffviewDelete              = { bg = p.diff_delete, bold = true },
        DiffviewText                = { bg = p.diff_text, bold = true },
        DiffAdd                     = { fg = p.git_add, bg = p.diff_add, bold = true },
        DiffChange                  = { bg = p.diff_change },
        DiffDelete                  = { fg = p.git_delete, bg = p.diff_delete },
        DiffText                    = { bg = p.diff_text },

        -- Telescope
        TelescopeBorder             = { fg = p.border },
        TelescopePromptBorder       = { fg = p.border },
        TelescopeResultsBorder      = { fg = p.border },
        TelescopePreviewBorder      = { fg = p.border },
        TelescopeSelection          = { bg = p.selection },
        TelescopeMultiSelection     = { bg = p.selection },

        -- NvimTree
        NvimTreeNormal              = { fg = p.fg, bg = p.bg_darker },
        NvimTreeFolderName          = { fg = p.blue },
        NvimTreeFolderIcon          = { fg = p.blue },
        NvimTreeOpenedFolderName    = { fg = p.blue },
        NvimTreeRootFolder          = { fg = p.purple, bold = true },
        NvimTreeGitDirty            = { fg = p.git_change },
        NvimTreeGitNew              = { fg = p.git_add },
        NvimTreeGitDeleted          = { fg = p.git_delete },

        -- Which-key
        WhichKey                    = { fg = p.purple },
        WhichKeyGroup               = { fg = p.blue },
        WhichKeyDesc                = { fg = p.fg },
        WhichKeySeparator           = { fg = p.comment },
        WhichKeyFloat               = { bg = p.bg_lighter },

        -- Indent-blankline
        IndentBlanklineChar         = { fg = p.border },
        IndentBlanklineContextChar  = { fg = p.fg_dim },

        -- Dashboard
        DashboardHeader             = { fg = p.purple },
        DashboardCenter             = { fg = p.blue },
        DashboardShortCut           = { fg = p.cyan_light },
        DashboardFooter             = { fg = p.comment },

        -- Notify
        NotifyERRORBorder           = { fg = p.error },
        NotifyWARNBorder            = { fg = p.warning },
        NotifyINFOBorder            = { fg = p.info },
        NotifyDEBUGBorder           = { fg = p.hint },
        NotifyTRACEBorder           = { fg = p.purple },
        NotifyERRORIcon             = { fg = p.error },
        NotifyWARNIcon              = { fg = p.warning },
        NotifyINFOIcon              = { fg = p.info },
        NotifyDEBUGIcon             = { fg = p.hint },
        NotifyTRACEIcon             = { fg = p.purple },
        NotifyERRORTitle            = { fg = p.error },
        NotifyWARNTitle             = { fg = p.warning },
        NotifyINFOTitle             = { fg = p.info },
        NotifyDEBUGTitle            = { fg = p.hint },
        NotifyTRACETitle            = { fg = p.purple },

        -- Neo-tree
        NeoTreeNormal               = { fg = p.fg, bg = p.bg_darker },
        NeoTreeNormalNC             = { fg = p.fg, bg = p.bg_darker },
        NeoTreeDirectoryName        = { fg = p.blue },
        NeoTreeDirectoryIcon        = { fg = p.blue },
        NeoTreeRootName             = { fg = p.purple, bold = true },
        NeoTreeGitAdded             = { fg = p.git_add },
        NeoTreeGitModified          = { fg = p.git_change },
        NeoTreeGitDeleted           = { fg = p.git_delete },

        -- Cmp (completion menu)
        CmpItemAbbrMatch            = { fg = p.blue },
        CmpItemAbbrMatchFuzzy       = { fg = p.blue },
        CmpItemKindVariable         = { fg = p.fg },
        CmpItemKindInterface        = { fg = p.orange },
        CmpItemKindText             = { fg = p.fg },
        CmpItemKindFunction         = { fg = p.purple },
        CmpItemKindMethod           = { fg = p.purple },
        CmpItemKindKeyword          = { fg = p.red },
        CmpItemKindProperty         = { fg = p.fg },
        CmpItemKindUnit             = { fg = p.blue },

        -- Bufferline
        BufferLineFill              = { bg = p.bg_darker },
        BufferLineBackground        = { fg = p.fg_dim, bg = p.bg_darker },
        BufferLineBuffer            = { fg = p.fg_dim, bg = p.bg_darker },
        BufferLineBufferSelected    = { fg = p.fg, bg = p.bg, bold = true },
        BufferLineBufferVisible     = { fg = p.fg, bg = p.bg_lighter },
        BufferLineTab               = { fg = p.fg_dim, bg = p.bg_darker },
        BufferLineTabSelected       = { fg = p.fg, bg = p.bg },
        BufferLineTabClose          = { fg = p.red, bg = p.bg_darker },

        -- Leap
        LeapMatch                   = { fg = p.bg, bg = p.purple, bold = true },
        LeapLabelPrimary            = { fg = p.bg, bg = p.pink, bold = true },
        LeapLabelSecondary          = { fg = p.bg, bg = p.cyan_light, bold = true },
        LeapBackdrop                = { fg = p.comment },

        -- Blink.cmp
        BlinkCmpMenu                = { fg = p.fg, bg = p.bg_lighter },
        BlinkCmpMenuBorder          = { fg = p.border, bg = p.bg_lighter },

        BlinkCmpDoc                 = { fg = p.fg, bg = p.bg_lighter },
        BlinkCmpDocBorder           = { link = 'FloatBorder' },
        BlinkCmpDocSeparator        = { link = 'FloatBorder' },

        BlinkCmpSource              = { link = 'Comment' },

        BlinkCmpLabel               = { fg = p.fg },
        BlinkCmpLabelDeprecated     = { fg = p.fg_dim, strikethrough = true },
        BlinkCmpLabelMatch          = { fg = p.purple },
        BlinkCmpLabelDetail         = { fg = p.comment },
        BlinkCmpLabelDescription    = { link = 'BlinkCmpLabelDetail' },

        BlinkCmpKind                = { fg = p.fg_dim, },
        BlinkCmpKindKeyword         = { link = 'Keyword' },
        BlinkCmpKindVariable        = { link = '@variable' },
        BlinkCmpKindConstant        = { link = '@constant' },
        BlinkCmpKindReference       = { link = 'Keyword' },
        BlinkCmpKindValue           = { link = 'Keyword' },


        BlinkCmpKindFunction          = { link = 'Function' },
        BlinkCmpKindMethod            = { link = 'Function' },
        BlinkCmpKindConstructor       = { link = '@constructor' },
        BlinkCmpKindInterface         = { link = 'Constant' },
        BlinkCmpKindEvent             = { link = 'Constant' },
        BlinkCmpKindEnum              = { link = 'Constant' },
        BlinkCmpKindUnit              = { link = 'Constant' },
        BlinkCmpKindClass             = { link = 'Type' },
        BlinkCmpKindStruct            = { link = 'Type' },
        BlinkCmpKindModule            = { link = '@module' },
        BlinkCmpKindProperty          = { link = '@property' },
        BlinkCmpKindField             = { link = '@variable.member' },
        BlinkCmpKindTypeParameter     = { link = '@variable.member' },
        BlinkCmpKindEnumMember        = { link = '@variable.member' },
        BlinkCmpKindOperator          = { link = 'Operator' },
        BlinkCmpKindSnippet           = { fg = p.fg_dim },

        -- Snacks nvim
        SnacksPicker                  = { link = 'Normal' },
        SnacksPickerBorder            = { fg = p.border },
        SnacksPickerDir               = { fg = p.none, bg = p.none, nocombine = true },
        SnacksPickerDirectory         = { fg = p.none, bg = p.none, nocombine = true },
        SnacksIndent                  = { fg = p.comment, bg = p.none, nocombine = true },
        SnacksPickerListCursorLine    = { link = 'PmenuSel' },
        SnacksPickerPreviewCursorLine = { fg = p.none, bg = p.none, nocombine = true },

        -- Treesitter Context
        TreesitterContext             = { bg = p.bg },
        TreesitterContextBottom       = { sp = p.visual, underline = true },

        -- Oil
        OilHidden                     = { fg = p.comment }

    }
end

return M
