# Colors (One Dark)

# Default colors
[colors.primary]
background = '#1f2329'
foreground = '#a0a8b7'

# Normal colors
[colors.normal]
black   = '#323641'
red     = '#e55561'
green   = '#8ebd6b'
yellow  = '#cc9057'
blue    = '#4fa6ed'
magenta = '#bf68d9'
cyan    = '#48b0bd'
white   = '#a0a8b7'

# Bright colors
[colors.bright]
black   = '#5c6370'
red     = '#e55561'
green   = '#8ebd6b'
yellow  = '#cc9057'
blue    = '#4fa6ed'
magenta = '#bf68d9'
cyan    = '#48b0bd'
white   = '#a0a8b7'
