[colors]
ansi = [
    '#3B4252',
    '#BF616A',
    '#A3BE8C',
    '#EBCB8B',
    '#81A1C1',
    '#B988B0',
    '#88C0D0',
    '#E5E9F0',
]
background = '#2E3440'
brights = [
    '#4C566A',
    '#BF616A',  
    '#A3BE8C',
    '#EBCB8B',
    '#81A1C1',
    '#B988B0',
    '#8FBCBB',
    '#ECEFF4',
]
cursor_bg = '#C8D0E0'
cursor_fg = '#2E3440'
foreground = '#C8D0E0'
selection_bg = '#3F4758'
selection_fg = '#E5E9F0'

[metadata]
author = 'Tom Marien'
name = 'One Nord (dark)'
