# Yukinord Dark
thm_bg="#1c212a";
thm_fg="#d8dee9";
thm_active_pane_fg="#1c212a";
thm_active_pane_bg="#5e81ac";
thm_inactive_pane_fg="#81a1c1";
thm_inactive_pane_bg="#1c212a";
thm_command_mode_bg="#ebcb8b";
thm_selection_fg="#d8dee9";
thm_selection_bg="#4c566a";
