# Fonts
font_family      family="JetBrainsMono Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 17

font_features JetBrainsMonoNFM-Regular +ss19
font_features JetBrainsMonoNFM-Bold +ss19
font_features JetBrainsMonoNFM-BoldItalic +ss19
font_features JetBrainsMonoNFM-Italic +ss19

modify_font cell_height 110%
modify_font cell_width -1px

# 2.0 = thickness dark on light (default 1.7)
# 20 = contrast, impact on dark themes (default 30)
text_composition_strategy 2.0 30

# Cursor
cursor_trail 3
cursor_trail_decay 0.1 0.2

# Symbols
# Material Design Icons
# symbol_map U+f0001-U+f1af0 Symbols Nerd Font Mono

# Mouse
mouse_hide_wait 1.0
mouse_map left click ungrabbed no_op

# Window
window_padding_width 1
hide_window_decorations titlebar-only

# Background
# ctrl+shift+a>m and ctrl+shift+a>l
dynamic_background_opacity yes
background_opacity 0.92
background_blur 15 

# Keybinds
macos_option_as_alt yes

# shift-enter claude
map shift+enter send_text all \x1b\r

map ctrl+shift+minus change_font_size all -1.0
map ctrl+shift+underscore change_font_size all -1.0

# BEGIN_THEME
include github-plus-dark.conf
# END_THEME
